/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PerformanceMod = IDL.Record({
  'engineLevel' : IDL.Nat,
  'brakesLevel' : IDL.Nat,
  'nitro' : IDL.Bool,
  'suspensionLevel' : IDL.Nat,
});
export const PaintMod = IDL.Record({ 'color' : IDL.Text, 'finish' : IDL.Text });
export const VisualMod = IDL.Record({
  'bodyKit' : IDL.Text,
  'rims' : IDL.Text,
  'underglowColor' : IDL.Opt(IDL.Text),
});
export const Modifications = IDL.Record({
  'performance' : IDL.Opt(PerformanceMod),
  'paint' : IDL.Opt(PaintMod),
  'visual' : IDL.Opt(VisualMod),
});
export const ChallengeId = IDL.Nat;
export const ChallengeDifficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'expert' : IDL.Null,
  'medium' : IDL.Null,
});
export const ChallengeType = IDL.Variant({
  'drag' : IDL.Null,
  'delivery' : IDL.Null,
  'drift' : IDL.Null,
  'circuit' : IDL.Null,
});
export const ChallengeRewards = IDL.Record({
  'currency' : IDL.Nat,
  'points' : IDL.Nat,
});
export const Challenge = IDL.Record({
  'id' : ChallengeId,
  'difficulty' : ChallengeDifficulty,
  'name' : IDL.Text,
  'challengeType' : ChallengeType,
  'rewards' : ChallengeRewards,
});
export const BaseStats = IDL.Record({
  'speed' : IDL.Nat,
  'acceleration' : IDL.Nat,
  'braking' : IDL.Nat,
  'handling' : IDL.Nat,
});
export const PlayerId = IDL.Principal;
export const LeaderboardEntry = IDL.Record({
  'playerId' : PlayerId,
  'rank' : IDL.Nat,
  'challengesCompleted' : IDL.Nat,
  'level' : IDL.Nat,
  'playerName' : IDL.Text,
  'totalPoints' : IDL.Nat,
});
export const Medal = IDL.Variant({
  'bronze' : IDL.Null,
  'gold' : IDL.Null,
  'silver' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ChallengeCompletion = IDL.Record({
  'medal' : Medal,
  'completedAt' : Timestamp,
  'timeMs' : IDL.Nat,
  'playerId' : PlayerId,
  'pointsEarned' : IDL.Nat,
  'challengeId' : ChallengeId,
});
export const VehicleId = IDL.Nat;
export const OwnedVehicle = IDL.Record({
  'modifications' : Modifications,
  'vehicleId' : VehicleId,
});
export const PlayerProfilePublic = IDL.Record({
  'id' : PlayerId,
  'vehicleIds' : IDL.Vec(VehicleId),
  'name' : IDL.Text,
  'level' : IDL.Nat,
  'totalPoints' : IDL.Nat,
  'currencyBalance' : IDL.Nat,
});
export const VehicleType = IDL.Variant({
  'car' : IDL.Null,
  'rickshaw' : IDL.Null,
  'motorcycle' : IDL.Null,
});
export const Vehicle = IDL.Record({
  'id' : VehicleId,
  'vehicleType' : VehicleType,
  'name' : IDL.Text,
  'baseStats' : BaseStats,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'applyMods' : IDL.Func([IDL.Nat, Modifications], [IDL.Bool], []),
  'getChallenge' : IDL.Func([IDL.Nat], [IDL.Opt(Challenge)], ['query']),
  'getEffectiveStats' : IDL.Func(
      [IDL.Nat, Modifications],
      [IDL.Opt(BaseStats)],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getMyCompletions' : IDL.Func([], [IDL.Vec(ChallengeCompletion)], ['query']),
  'getMyGarage' : IDL.Func([], [IDL.Vec(OwnedVehicle)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(PlayerProfilePublic)], ['query']),
  'getProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PlayerProfilePublic)],
      ['query'],
    ),
  'getVehicle' : IDL.Func([IDL.Nat], [IDL.Opt(Vehicle)], ['query']),
  'listChallenges' : IDL.Func([], [IDL.Vec(Challenge)], ['query']),
  'listVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'purchaseVehicle' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'registerPlayer' : IDL.Func([IDL.Text], [PlayerProfilePublic], []),
  'submitChallengeResult' : IDL.Func(
      [IDL.Nat, IDL.Nat, Medal],
      [ChallengeCompletion],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PerformanceMod = IDL.Record({
    'engineLevel' : IDL.Nat,
    'brakesLevel' : IDL.Nat,
    'nitro' : IDL.Bool,
    'suspensionLevel' : IDL.Nat,
  });
  const PaintMod = IDL.Record({ 'color' : IDL.Text, 'finish' : IDL.Text });
  const VisualMod = IDL.Record({
    'bodyKit' : IDL.Text,
    'rims' : IDL.Text,
    'underglowColor' : IDL.Opt(IDL.Text),
  });
  const Modifications = IDL.Record({
    'performance' : IDL.Opt(PerformanceMod),
    'paint' : IDL.Opt(PaintMod),
    'visual' : IDL.Opt(VisualMod),
  });
  const ChallengeId = IDL.Nat;
  const ChallengeDifficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'expert' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ChallengeType = IDL.Variant({
    'drag' : IDL.Null,
    'delivery' : IDL.Null,
    'drift' : IDL.Null,
    'circuit' : IDL.Null,
  });
  const ChallengeRewards = IDL.Record({
    'currency' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const Challenge = IDL.Record({
    'id' : ChallengeId,
    'difficulty' : ChallengeDifficulty,
    'name' : IDL.Text,
    'challengeType' : ChallengeType,
    'rewards' : ChallengeRewards,
  });
  const BaseStats = IDL.Record({
    'speed' : IDL.Nat,
    'acceleration' : IDL.Nat,
    'braking' : IDL.Nat,
    'handling' : IDL.Nat,
  });
  const PlayerId = IDL.Principal;
  const LeaderboardEntry = IDL.Record({
    'playerId' : PlayerId,
    'rank' : IDL.Nat,
    'challengesCompleted' : IDL.Nat,
    'level' : IDL.Nat,
    'playerName' : IDL.Text,
    'totalPoints' : IDL.Nat,
  });
  const Medal = IDL.Variant({
    'bronze' : IDL.Null,
    'gold' : IDL.Null,
    'silver' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ChallengeCompletion = IDL.Record({
    'medal' : Medal,
    'completedAt' : Timestamp,
    'timeMs' : IDL.Nat,
    'playerId' : PlayerId,
    'pointsEarned' : IDL.Nat,
    'challengeId' : ChallengeId,
  });
  const VehicleId = IDL.Nat;
  const OwnedVehicle = IDL.Record({
    'modifications' : Modifications,
    'vehicleId' : VehicleId,
  });
  const PlayerProfilePublic = IDL.Record({
    'id' : PlayerId,
    'vehicleIds' : IDL.Vec(VehicleId),
    'name' : IDL.Text,
    'level' : IDL.Nat,
    'totalPoints' : IDL.Nat,
    'currencyBalance' : IDL.Nat,
  });
  const VehicleType = IDL.Variant({
    'car' : IDL.Null,
    'rickshaw' : IDL.Null,
    'motorcycle' : IDL.Null,
  });
  const Vehicle = IDL.Record({
    'id' : VehicleId,
    'vehicleType' : VehicleType,
    'name' : IDL.Text,
    'baseStats' : BaseStats,
    'brand' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'applyMods' : IDL.Func([IDL.Nat, Modifications], [IDL.Bool], []),
    'getChallenge' : IDL.Func([IDL.Nat], [IDL.Opt(Challenge)], ['query']),
    'getEffectiveStats' : IDL.Func(
        [IDL.Nat, Modifications],
        [IDL.Opt(BaseStats)],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getMyCompletions' : IDL.Func(
        [],
        [IDL.Vec(ChallengeCompletion)],
        ['query'],
      ),
    'getMyGarage' : IDL.Func([], [IDL.Vec(OwnedVehicle)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(PlayerProfilePublic)], ['query']),
    'getProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerProfilePublic)],
        ['query'],
      ),
    'getVehicle' : IDL.Func([IDL.Nat], [IDL.Opt(Vehicle)], ['query']),
    'listChallenges' : IDL.Func([], [IDL.Vec(Challenge)], ['query']),
    'listVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'purchaseVehicle' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'registerPlayer' : IDL.Func([IDL.Text], [PlayerProfilePublic], []),
    'submitChallengeResult' : IDL.Func(
        [IDL.Nat, IDL.Nat, Medal],
        [ChallengeCompletion],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };