/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BaseStats {
  'speed' : bigint,
  'acceleration' : bigint,
  'braking' : bigint,
  'handling' : bigint,
}
export interface Challenge {
  'id' : ChallengeId,
  'difficulty' : ChallengeDifficulty,
  'name' : string,
  'challengeType' : ChallengeType,
  'rewards' : ChallengeRewards,
}
export interface ChallengeCompletion {
  'medal' : Medal,
  'completedAt' : Timestamp,
  'timeMs' : bigint,
  'playerId' : PlayerId,
  'pointsEarned' : bigint,
  'challengeId' : ChallengeId,
}
export type ChallengeDifficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'expert' : null } |
  { 'medium' : null };
export type ChallengeId = bigint;
export interface ChallengeRewards { 'currency' : bigint, 'points' : bigint }
export type ChallengeType = { 'drag' : null } |
  { 'delivery' : null } |
  { 'drift' : null } |
  { 'circuit' : null };
export interface LeaderboardEntry {
  'playerId' : PlayerId,
  'rank' : bigint,
  'challengesCompleted' : bigint,
  'level' : bigint,
  'playerName' : string,
  'totalPoints' : bigint,
}
export type Medal = { 'bronze' : null } |
  { 'gold' : null } |
  { 'silver' : null };
export interface Modifications {
  'performance' : [] | [PerformanceMod],
  'paint' : [] | [PaintMod],
  'visual' : [] | [VisualMod],
}
export interface OwnedVehicle {
  'modifications' : Modifications,
  'vehicleId' : VehicleId,
}
export interface PaintMod { 'color' : string, 'finish' : string }
export interface PerformanceMod {
  'engineLevel' : bigint,
  'brakesLevel' : bigint,
  'nitro' : boolean,
  'suspensionLevel' : bigint,
}
export type PlayerId = Principal;
export interface PlayerProfilePublic {
  'id' : PlayerId,
  'vehicleIds' : Array<VehicleId>,
  'name' : string,
  'level' : bigint,
  'totalPoints' : bigint,
  'currencyBalance' : bigint,
}
export type Timestamp = bigint;
export interface Vehicle {
  'id' : VehicleId,
  'vehicleType' : VehicleType,
  'name' : string,
  'baseStats' : BaseStats,
  'brand' : string,
  'price' : bigint,
}
export type VehicleId = bigint;
export type VehicleType = { 'car' : null } |
  { 'rickshaw' : null } |
  { 'motorcycle' : null };
export interface VisualMod {
  'bodyKit' : string,
  'rims' : string,
  'underglowColor' : [] | [string],
}
export interface _SERVICE {
  'applyMods' : ActorMethod<[bigint, Modifications], boolean>,
  'getChallenge' : ActorMethod<[bigint], [] | [Challenge]>,
  'getEffectiveStats' : ActorMethod<[bigint, Modifications], [] | [BaseStats]>,
  'getLeaderboard' : ActorMethod<[bigint], Array<LeaderboardEntry>>,
  'getMyCompletions' : ActorMethod<[], Array<ChallengeCompletion>>,
  'getMyGarage' : ActorMethod<[], Array<OwnedVehicle>>,
  'getMyProfile' : ActorMethod<[], [] | [PlayerProfilePublic]>,
  'getProfile' : ActorMethod<[Principal], [] | [PlayerProfilePublic]>,
  'getVehicle' : ActorMethod<[bigint], [] | [Vehicle]>,
  'listChallenges' : ActorMethod<[], Array<Challenge>>,
  'listVehicles' : ActorMethod<[], Array<Vehicle>>,
  'purchaseVehicle' : ActorMethod<[bigint], boolean>,
  'registerPlayer' : ActorMethod<[string], PlayerProfilePublic>,
  'submitChallengeResult' : ActorMethod<
    [bigint, bigint, Medal],
    ChallengeCompletion
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];