/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PaintMod {
    color: string;
    finish: string;
}
export interface LeaderboardEntry {
    playerId: PlayerId;
    rank: bigint;
    challengesCompleted: bigint;
    level: bigint;
    playerName: string;
    totalPoints: bigint;
}
export type Timestamp = bigint;
export type VehicleId = bigint;
export interface PerformanceMod {
    engineLevel: bigint;
    brakesLevel: bigint;
    nitro: boolean;
    suspensionLevel: bigint;
}
export type ChallengeId = bigint;
export interface VisualMod {
    bodyKit: string;
    rims: string;
    underglowColor?: string;
}
export interface Vehicle {
    id: VehicleId;
    vehicleType: VehicleType;
    name: string;
    baseStats: BaseStats;
    brand: string;
    price: bigint;
}
export interface PlayerProfilePublic {
    id: PlayerId;
    vehicleIds: Array<VehicleId>;
    name: string;
    level: bigint;
    totalPoints: bigint;
    currencyBalance: bigint;
}
export interface OwnedVehicle {
    modifications: Modifications;
    vehicleId: VehicleId;
}
export type PlayerId = Principal;
export interface ChallengeCompletion {
    medal: Medal;
    completedAt: Timestamp;
    timeMs: bigint;
    playerId: PlayerId;
    pointsEarned: bigint;
    challengeId: ChallengeId;
}
export interface Challenge {
    id: ChallengeId;
    difficulty: ChallengeDifficulty;
    name: string;
    challengeType: ChallengeType;
    rewards: ChallengeRewards;
}
export interface Modifications {
    performance?: PerformanceMod;
    paint?: PaintMod;
    visual?: VisualMod;
}
export interface ChallengeRewards {
    currency: bigint;
    points: bigint;
}
export interface BaseStats {
    speed: bigint;
    acceleration: bigint;
    braking: bigint;
    handling: bigint;
}
export enum ChallengeDifficulty {
    easy = "easy",
    hard = "hard",
    expert = "expert",
    medium = "medium"
}
export enum ChallengeType {
    drag = "drag",
    delivery = "delivery",
    drift = "drift",
    circuit = "circuit"
}
export enum Medal {
    bronze = "bronze",
    gold = "gold",
    silver = "silver"
}
export enum VehicleType {
    car = "car",
    rickshaw = "rickshaw",
    motorcycle = "motorcycle"
}
export interface backendInterface {
    applyMods(vehicleId: bigint, mods: Modifications): Promise<boolean>;
    getChallenge(id: bigint): Promise<Challenge | null>;
    getEffectiveStats(id: bigint, mods: Modifications): Promise<BaseStats | null>;
    getLeaderboard(topN: bigint): Promise<Array<LeaderboardEntry>>;
    getMyCompletions(): Promise<Array<ChallengeCompletion>>;
    getMyGarage(): Promise<Array<OwnedVehicle>>;
    getMyProfile(): Promise<PlayerProfilePublic | null>;
    getProfile(playerId: Principal): Promise<PlayerProfilePublic | null>;
    getVehicle(id: bigint): Promise<Vehicle | null>;
    listChallenges(): Promise<Array<Challenge>>;
    listVehicles(): Promise<Array<Vehicle>>;
    purchaseVehicle(vehicleId: bigint): Promise<boolean>;
    registerPlayer(name: string): Promise<PlayerProfilePublic>;
    submitChallengeResult(challengeId: bigint, timeMs: bigint, medal: Medal): Promise<ChallengeCompletion>;
}
import type { BaseStats as _BaseStats, Challenge as _Challenge, ChallengeCompletion as _ChallengeCompletion, ChallengeDifficulty as _ChallengeDifficulty, ChallengeId as _ChallengeId, ChallengeRewards as _ChallengeRewards, ChallengeType as _ChallengeType, Medal as _Medal, Modifications as _Modifications, OwnedVehicle as _OwnedVehicle, PaintMod as _PaintMod, PerformanceMod as _PerformanceMod, PlayerId as _PlayerId, PlayerProfilePublic as _PlayerProfilePublic, Timestamp as _Timestamp, Vehicle as _Vehicle, VehicleId as _VehicleId, VehicleType as _VehicleType, VisualMod as _VisualMod } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async applyMods(arg0: bigint, arg1: Modifications): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.applyMods(arg0, to_candid_Modifications_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyMods(arg0, to_candid_Modifications_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getChallenge(arg0: bigint): Promise<Challenge | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallenge(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallenge(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEffectiveStats(arg0: bigint, arg1: Modifications): Promise<BaseStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEffectiveStats(arg0, to_candid_Modifications_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEffectiveStats(arg0, to_candid_Modifications_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(arg0: bigint): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(arg0);
            return result;
        }
    }
    async getMyCompletions(): Promise<Array<ChallengeCompletion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCompletions();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCompletions();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyGarage(): Promise<Array<OwnedVehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyGarage();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyGarage();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<PlayerProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: Principal): Promise<PlayerProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVehicle(arg0: bigint): Promise<Vehicle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVehicle(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVehicle(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listChallenges(): Promise<Array<Challenge>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChallenges();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChallenges();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVehicles(): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVehicles();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVehicles();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async purchaseVehicle(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseVehicle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseVehicle(arg0);
            return result;
        }
    }
    async registerPlayer(arg0: string): Promise<PlayerProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerPlayer(arg0);
            return result;
        }
    }
    async submitChallengeResult(arg0: bigint, arg1: bigint, arg2: Medal): Promise<ChallengeCompletion> {
        if (this.processError) {
            try {
                const result = await this.actor.submitChallengeResult(arg0, arg1, to_candid_Medal_n37(this._uploadFile, this._downloadFile, arg2));
                return from_candid_ChallengeCompletion_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitChallengeResult(arg0, arg1, to_candid_Medal_n37(this._uploadFile, this._downloadFile, arg2));
            return from_candid_ChallengeCompletion_n14(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ChallengeCompletion_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChallengeCompletion): ChallengeCompletion {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ChallengeDifficulty_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChallengeDifficulty): ChallengeDifficulty {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ChallengeType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChallengeType): ChallengeType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Challenge_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Challenge): Challenge {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Medal_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Medal): Medal {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Modifications_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Modifications): Modifications {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_OwnedVehicle_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OwnedVehicle): OwnedVehicle {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleType): VehicleType {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Vehicle_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vehicle): Vehicle {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_VisualMod_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisualMod): VisualMod {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BaseStats]): BaseStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PerformanceMod]): PerformanceMod | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaintMod]): PaintMod | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VisualMod]): VisualMod | null {
    return value.length === 0 ? null : from_candid_VisualMod_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerProfilePublic]): PlayerProfilePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Vehicle]): Vehicle | null {
    return value.length === 0 ? null : from_candid_Vehicle_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Challenge]): Challenge | null {
    return value.length === 0 ? null : from_candid_Challenge_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    medal: _Medal;
    completedAt: _Timestamp;
    timeMs: bigint;
    playerId: _PlayerId;
    pointsEarned: bigint;
    challengeId: _ChallengeId;
}): {
    medal: Medal;
    completedAt: Timestamp;
    timeMs: bigint;
    playerId: PlayerId;
    pointsEarned: bigint;
    challengeId: ChallengeId;
} {
    return {
        medal: from_candid_Medal_n16(_uploadFile, _downloadFile, value.medal),
        completedAt: value.completedAt,
        timeMs: value.timeMs,
        playerId: value.playerId,
        pointsEarned: value.pointsEarned,
        challengeId: value.challengeId
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    modifications: _Modifications;
    vehicleId: _VehicleId;
}): {
    modifications: Modifications;
    vehicleId: VehicleId;
} {
    return {
        modifications: from_candid_Modifications_n21(_uploadFile, _downloadFile, value.modifications),
        vehicleId: value.vehicleId
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    performance: [] | [_PerformanceMod];
    paint: [] | [_PaintMod];
    visual: [] | [_VisualMod];
}): {
    performance?: PerformanceMod;
    paint?: PaintMod;
    visual?: VisualMod;
} {
    return {
        performance: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.performance)),
        paint: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.paint)),
        visual: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.visual))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bodyKit: string;
    rims: string;
    underglowColor: [] | [string];
}): {
    bodyKit: string;
    rims: string;
    underglowColor?: string;
} {
    return {
        bodyKit: value.bodyKit,
        rims: value.rims,
        underglowColor: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.underglowColor))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VehicleId;
    vehicleType: _VehicleType;
    name: string;
    baseStats: _BaseStats;
    brand: string;
    price: bigint;
}): {
    id: VehicleId;
    vehicleType: VehicleType;
    name: string;
    baseStats: BaseStats;
    brand: string;
    price: bigint;
} {
    return {
        id: value.id,
        vehicleType: from_candid_VehicleType_n33(_uploadFile, _downloadFile, value.vehicleType),
        name: value.name,
        baseStats: value.baseStats,
        brand: value.brand,
        price: value.price
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ChallengeId;
    difficulty: _ChallengeDifficulty;
    name: string;
    challengeType: _ChallengeType;
    rewards: _ChallengeRewards;
}): {
    id: ChallengeId;
    difficulty: ChallengeDifficulty;
    name: string;
    challengeType: ChallengeType;
    rewards: ChallengeRewards;
} {
    return {
        id: value.id,
        difficulty: from_candid_ChallengeDifficulty_n8(_uploadFile, _downloadFile, value.difficulty),
        name: value.name,
        challengeType: from_candid_ChallengeType_n10(_uploadFile, _downloadFile, value.challengeType),
        rewards: value.rewards
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    drag: null;
} | {
    delivery: null;
} | {
    drift: null;
} | {
    circuit: null;
}): ChallengeType {
    return "drag" in value ? ChallengeType.drag : "delivery" in value ? ChallengeType.delivery : "drift" in value ? ChallengeType.drift : "circuit" in value ? ChallengeType.circuit : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bronze: null;
} | {
    gold: null;
} | {
    silver: null;
}): Medal {
    return "bronze" in value ? Medal.bronze : "gold" in value ? Medal.gold : "silver" in value ? Medal.silver : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    car: null;
} | {
    rickshaw: null;
} | {
    motorcycle: null;
}): VehicleType {
    return "car" in value ? VehicleType.car : "rickshaw" in value ? VehicleType.rickshaw : "motorcycle" in value ? VehicleType.motorcycle : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    expert: null;
} | {
    medium: null;
}): ChallengeDifficulty {
    return "easy" in value ? ChallengeDifficulty.easy : "hard" in value ? ChallengeDifficulty.hard : "expert" in value ? ChallengeDifficulty.expert : "medium" in value ? ChallengeDifficulty.medium : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChallengeCompletion>): Array<ChallengeCompletion> {
    return value.map((x)=>from_candid_ChallengeCompletion_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OwnedVehicle>): Array<OwnedVehicle> {
    return value.map((x)=>from_candid_OwnedVehicle_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Challenge>): Array<Challenge> {
    return value.map((x)=>from_candid_Challenge_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Vehicle>): Array<Vehicle> {
    return value.map((x)=>from_candid_Vehicle_n31(_uploadFile, _downloadFile, x));
}
function to_candid_Medal_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Medal): _Medal {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_Modifications_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Modifications): _Modifications {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_VisualMod_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VisualMod): _VisualMod {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    performance?: PerformanceMod;
    paint?: PaintMod;
    visual?: VisualMod;
}): {
    performance: [] | [_PerformanceMod];
    paint: [] | [_PaintMod];
    visual: [] | [_VisualMod];
} {
    return {
        performance: value.performance ? candid_some(value.performance) : candid_none(),
        paint: value.paint ? candid_some(value.paint) : candid_none(),
        visual: value.visual ? candid_some(to_candid_VisualMod_n3(_uploadFile, _downloadFile, value.visual)) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bodyKit: string;
    rims: string;
    underglowColor?: string;
}): {
    bodyKit: string;
    rims: string;
    underglowColor: [] | [string];
} {
    return {
        bodyKit: value.bodyKit,
        rims: value.rims,
        underglowColor: value.underglowColor ? candid_some(value.underglowColor) : candid_none()
    };
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Medal): {
    bronze: null;
} | {
    gold: null;
} | {
    silver: null;
} {
    return value == Medal.bronze ? {
        bronze: null
    } : value == Medal.gold ? {
        gold: null
    } : value == Medal.silver ? {
        silver: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
